#! /bin/sh

###---Autostart---###
xrdb ~/.Xresources &
sxhkd &
~/.config/polybar/launch.sh &
feh --bg-fill ~/.config/wall.png &
compton &


###---MONITORS---###
bspc monitor -d 1 2 3 4 5 6 7 8 9 0


###---Monitor And Desktop Settings----###
bspc config top_padding 32
bspc config bottom_padding 6
bspc config left_padding 6
bspc config right_padding 6
bspc config border_width 0
bspc config window_gap 3

# Configuration
bspc config split_ratio          0.50

# Mouse
bspc config click_to_focus	 button1


# Colors
# bspc config normal_border_color		"#000000"
# bspc config focused_border_color	"#000000"
bspc config presel_feedback_color	"#5e81ac"


bspc desktop 4 -l monocle
# Rules
bspc rule -a firefox desktop='^1' follow=on
bspc rule -a Thunar desktop='^2' follow=on
# bspc rule -a *:*:ranger state=floating rectangle=900x500+900+200
bspc rule -a Alacritty:Alacritty:lf desktop='^2' follow=on
bspc rule -a Urxvt:lf desktop='^3' follow=on focus=on

bspc rule -a Alacritty desktop='^3' follow=on
bspc rule -a code-oss desktop='^4' follow=on 
bspc rule -a Soffice desktop='^5' follow=on
bspc rule -a Zathura desktop='^6' follow=on
bspc rule -a feh focus=off state=floating
bspc rule -a Gimp desktop='^8' state=floating 
bspc rule -a Transmission-gtk desktop='^9' follow=on
bspc rule -a mpv desktop='^10' follow=on state=fullscreen
#bspc rule -a * desktop='^0' follow=on
